# Beauty Store - Student Practice Notebook

Dataset file: `05_beauty_store.csv`

Solve each task in the empty code cell below it.

## Task 1

Load the dataset into a pandas DataFrame.

In [77]:
import pandas as pd
df=pd.read_csv("05_beauty_store.csv")

## Task 2

Display the first 10 rows of the DataFrame.

In [78]:
df.head(10)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value
0,05ORD100522,2024-10-14,Salon,North,Skincare,Credit Card,2,2460.12,23,3788.58
1,05ORD100738,2025-05-30,Salon,Central,Skincare,Wallet,4,4998.47,36,12796.08
2,05ORD100741,2025-03-06,Premium,West,Makeup,Credit Card,5,2486.68,35,8081.71
3,05ORD100661,2025-08-09,Salon,South,Skincare,Credit Card,2,1274.18,10,2293.52
4,05ORD100412,2025-08-25,Salon,West,Fragrance,Credit Card,2,2581.16,31,3562.00
5,05ORD100679,2024-03-15,First-Time,East,Fragrance,Debit Card,1,212.37,15,180.51
6,05ORD100627,2025-12-21,Regular,Central,Skincare,Credit Card,2,3489.43,42,4047.74
7,05ORD100514,2025-02-18,Salon,North,Makeup,Cash on Delivery,3,1987.87,40,3578.17
8,05ORD100860,2024-02-12,Salon,North,Fragrance,Cash on Delivery,5,2449.84,2,12004.22
9,05ORD100137,2025-10-02,Premium,North,Skincare,Cash on Delivery,2,4275.19,19,6925.81

## Task 3

Display the last 7 rows of the DataFrame.

In [79]:
df.tail(7)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value
993,05ORD100701,2025-08-25,Regular,West,Fragrance,Wallet,3,4843.18,5,13803.06
994,05ORD100072,2024-07-23,Premium,East,Skincare,Wallet,4,2480.76,35,6449.98
995,05ORD100107,2024-11-23,First-Time,East,Skincare,Credit Card,1,521.25,25,390.94
996,05ORD100271,2025-05-18,Regular,West,Skincare,Wallet,3,4030.10,20,9672.24
997,05ORD100861,2024-04-27,Salon,East,Fragrance,Cash on Delivery,2,496.40,29,704.89
998,05ORD100436,2025-04-12,First-Time,East,Wellness,Debit Card,1,4702.95,26,3480.18
999,05ORD100103,2025-05-23,Salon,East,Makeup,Wallet,2,3805.41,21,6012.55

## Task 4

Check the shape of the DataFrame.

In [80]:
df.shape

(1000, 10)

## Task 5

List all column names.

In [81]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_Segment', 'Region',
       'Product_Category', 'Payment_Method', 'Quantity', 'Unit_Price',
       'Discount_Percent', 'Order_Value'],
      dtype='str')

## Task 6

Check the data types of all columns.

In [82]:
df.dtypes

Order_ID                str
Order_Date              str
Customer_Segment        str
Region                  str
Product_Category        str
Payment_Method          str
Quantity              int64
Unit_Price          float64
Discount_Percent      int64
Order_Value         float64
dtype: object

## Task 7

Display basic information using info().

In [83]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1000 non-null   str
 1   Order_Date        1000 non-null   str
 2   Customer_Segment  1000 non-null   str
 3   Region            1000 non-null   str
 4   Product_Category  1000 non-null   str
 5   Payment_Method    1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Unit_Price        1000 non-null   float64
 8   Discount_Percent  1000 non-null   int64
 9   Order_Value       1000 non-null   float64
dtypes: float64(2), int64(2), str(6)
memory usage: 78.3 KB

## Task 8

Generate summary statistics for numerical columns.

In [84]:
df.describe()

          Quantity   Unit_Price  Discount_Percent   Order_Value
count  1000.000000  1000.000000       1000.000000   1000.000000
mean      2.460000  2559.763040         22.930000   4903.644860
std       1.443081  1448.333137         13.257106   4472.927876
min       1.000000   102.670000          0.000000     82.650000
25%       1.000000  1327.715000         11.000000   1557.750000
50%       2.000000  2552.150000         23.000000   3348.790000
75%       4.000000  3809.115000         35.000000   6794.790000
max       5.000000  4998.470000         45.000000  23943.240000

## Task 9

Generate summary statistics for categorical columns.

In [85]:
df.describe(include=object)

C:\Users\Chadagonda.Reddy\AppData\Local\Temp\ipykernel_35964\3998025828.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=object)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method
count,1000,1000,1000,1000,1000,1000
unique,1000,533,4,5,5,5
top,05ORD100522,2024-04-30,Regular,South,Fragrance,Wallet
freq,1,6,263,225,229,210

## Task 10

Check whether the DataFrame contains any missing values.

In [86]:
df.isna()

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False

## Task 11

Count the missing values in each column.

In [87]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_Segment    0
Region              0
Product_Category    0
Payment_Method      0
Quantity            0
Unit_Price          0
Discount_Percent    0
Order_Value         0
dtype: int64

## Task 12

Check whether there are any duplicate rows.

In [88]:
df.duplicated().any()

np.False_

## Task 13

Count the duplicate rows in the DataFrame.

In [89]:
df.duplicated().sum()

np.int64(0)

## Task 14

Drop duplicate rows if any exist.

In [90]:
df.drop_duplicates()

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value
0,05ORD100522,2024-10-14,Salon,North,Skincare,Credit Card,2,2460.12,23,3788.58
1,05ORD100738,2025-05-30,Salon,Central,Skincare,Wallet,4,4998.47,36,12796.08
2,05ORD100741,2025-03-06,Premium,West,Makeup,Credit Card,5,2486.68,35,8081.71
3,05ORD100661,2025-08-09,Salon,South,Skincare,Credit Card,2,1274.18,10,2293.52
4,05ORD100412,2025-08-25,Salon,West,Fragrance,Credit Card,2,2581.16,31,3562.00
...,...,...,...,...,...,...,...,...,...,...
995,05ORD100107,2024-11-23,First-Time,East,Skincare,Credit Card,1,521.25,25,390.94
996,05ORD100271,2025-05-18,Regular,West,Skincare,Wallet,3,4030.10,20,9672.24
997,05ORD100861,2024-04-27,Salon,East,Fragrance,Cash on Delivery,2,496.40,29,704.89
998,05ORD100436,2025-04-12,First-Time,East,Wellness,Debit Card,1,4702.95,26,3480.18
999,05ORD100103,2025-05-23,Salon,East,Makeup,Wallet,2,3805.41,21,6012.55

## Task 15

Convert the Order_Date column to datetime format.

In [91]:
df['Order_Date']=pd.to_datetime(df['Order_Date'])
print(df)

        Order_ID Order_Date Customer_Segment   Region Product_Category  \
0    05ORD100522 2024-10-14            Salon    North         Skincare
1    05ORD100738 2025-05-30            Salon  Central         Skincare
2    05ORD100741 2025-03-06          Premium     West           Makeup
3    05ORD100661 2025-08-09            Salon    South         Skincare
4    05ORD100412 2025-08-25            Salon     West        Fragrance
..           ...        ...              ...      ...              ...
995  05ORD100107 2024-11-23       First-Time     East         Skincare
996  05ORD100271 2025-05-18          Regular     West         Skincare
997  05ORD100861 2024-04-27            Salon     East        Fragrance
998  05ORD100436 2025-04-12       First-Time     East         Wellness
999  05ORD100103 2025-05-23            Salon     East           Makeup

       Payment_Method  Quantity  Unit_Price  Discount_Percent  Order_Value
0         Credit Card         2     2460.12                23      3788.58
1              Wallet         4     4998.47                36     12796.08
2         Credit Card         5     2486.68                35      8081.71
3         Credit Card         2     1274.18                10      2293.52
4         Credit Card         2     2581.16                31      3562.00
..                ...       ...         ...               ...          ...
995       Credit Card         1      521.25                25       390.94
996            Wallet         3     4030.10                20      9672.24
997  Cash on Delivery         2      496.40                29       704.89
998        Debit Card         1     4702.95                26      3480.18
999            Wallet         2     3805.41                21      6012.55

[1000 rows x 10 columns]

## Task 16

Extract only the year from Order_Date into a new column named Order_Year.

In [92]:
df['Order_Year']=df["Order_Date"].dt.year
df

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year
0,05ORD100522,2024-10-14,Salon,North,Skincare,Credit Card,2,2460.12,23,3788.58,2024
1,05ORD100738,2025-05-30,Salon,Central,Skincare,Wallet,4,4998.47,36,12796.08,2025
2,05ORD100741,2025-03-06,Premium,West,Makeup,Credit Card,5,2486.68,35,8081.71,2025
3,05ORD100661,2025-08-09,Salon,South,Skincare,Credit Card,2,1274.18,10,2293.52,2025
4,05ORD100412,2025-08-25,Salon,West,Fragrance,Credit Card,2,2581.16,31,3562.00,2025
...,...,...,...,...,...,...,...,...,...,...,...
995,05ORD100107,2024-11-23,First-Time,East,Skincare,Credit Card,1,521.25,25,390.94,2024
996,05ORD100271,2025-05-18,Regular,West,Skincare,Wallet,3,4030.10,20,9672.24,2025
997,05ORD100861,2024-04-27,Salon,East,Fragrance,Cash on Delivery,2,496.40,29,704.89,2024
998,05ORD100436,2025-04-12,First-Time,East,Wellness,Debit Card,1,4702.95,26,3480.18,2025
999,05ORD100103,2025-05-23,Salon,East,Makeup,Wallet,2,3805.41,21,6012.55,2025

## Task 17

Extract the month name from Order_Date into a new column named Order_Month.

In [93]:
df['Order_Month']=df["Order_Date"].dt.month_name()
df

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month
0,05ORD100522,2024-10-14,Salon,North,Skincare,Credit Card,2,2460.12,23,3788.58,2024,October
1,05ORD100738,2025-05-30,Salon,Central,Skincare,Wallet,4,4998.47,36,12796.08,2025,May
2,05ORD100741,2025-03-06,Premium,West,Makeup,Credit Card,5,2486.68,35,8081.71,2025,March
3,05ORD100661,2025-08-09,Salon,South,Skincare,Credit Card,2,1274.18,10,2293.52,2025,August
4,05ORD100412,2025-08-25,Salon,West,Fragrance,Credit Card,2,2581.16,31,3562.00,2025,August
...,...,...,...,...,...,...,...,...,...,...,...,...
995,05ORD100107,2024-11-23,First-Time,East,Skincare,Credit Card,1,521.25,25,390.94,2024,November
996,05ORD100271,2025-05-18,Regular,West,Skincare,Wallet,3,4030.10,20,9672.24,2025,May
997,05ORD100861,2024-04-27,Salon,East,Fragrance,Cash on Delivery,2,496.40,29,704.89,2024,April
998,05ORD100436,2025-04-12,First-Time,East,Wellness,Debit Card,1,4702.95,26,3480.18,2025,April
999,05ORD100103,2025-05-23,Salon,East,Makeup,Wallet,2,3805.41,21,6012.55,2025,May

## Task 18

Extract the weekday name from Order_Date into a new column named Order_Day.

In [94]:
df['Order_Day']=df["Order_Date"].dt.day_name()
df

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
0,05ORD100522,2024-10-14,Salon,North,Skincare,Credit Card,2,2460.12,23,3788.58,2024,October,Monday
1,05ORD100738,2025-05-30,Salon,Central,Skincare,Wallet,4,4998.47,36,12796.08,2025,May,Friday
2,05ORD100741,2025-03-06,Premium,West,Makeup,Credit Card,5,2486.68,35,8081.71,2025,March,Thursday
3,05ORD100661,2025-08-09,Salon,South,Skincare,Credit Card,2,1274.18,10,2293.52,2025,August,Saturday
4,05ORD100412,2025-08-25,Salon,West,Fragrance,Credit Card,2,2581.16,31,3562.00,2025,August,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,05ORD100107,2024-11-23,First-Time,East,Skincare,Credit Card,1,521.25,25,390.94,2024,November,Saturday
996,05ORD100271,2025-05-18,Regular,West,Skincare,Wallet,3,4030.10,20,9672.24,2025,May,Sunday
997,05ORD100861,2024-04-27,Salon,East,Fragrance,Cash on Delivery,2,496.40,29,704.89,2024,April,Saturday
998,05ORD100436,2025-04-12,First-Time,East,Wellness,Debit Card,1,4702.95,26,3480.18,2025,April,Saturday
999,05ORD100103,2025-05-23,Salon,East,Makeup,Wallet,2,3805.41,21,6012.55,2025,May,Friday

## Task 19

Display a random sample of 12 rows.

In [95]:
df.sample(12)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
28,05ORD100903,2024-02-01,First-Time,East,Makeup,Debit Card,2,3172.67,6,5964.62,2024,February,Thursday
423,05ORD100569,2024-05-15,Regular,Central,Wellness,UPI,5,2276.34,14,9788.26,2024,May,Wednesday
328,05ORD100712,2024-07-01,Premium,South,Fragrance,Cash on Delivery,5,4120.22,39,12566.67,2024,July,Monday
96,05ORD100765,2025-05-23,Premium,Central,Makeup,UPI,1,1532.15,16,1287.01,2025,May,Friday
733,05ORD100766,2024-11-05,First-Time,North,Haircare,Cash on Delivery,3,4207.21,0,12621.63,2024,November,Tuesday
6,05ORD100627,2025-12-21,Regular,Central,Skincare,Credit Card,2,3489.43,42,4047.74,2025,December,Sunday
794,05ORD100906,2025-07-23,Premium,Central,Haircare,Debit Card,1,782.14,10,703.93,2025,July,Wednesday
441,05ORD100573,2024-12-06,Regular,West,Wellness,Debit Card,4,435.11,19,1409.76,2024,December,Friday
978,05ORD100309,2024-02-24,Premium,West,Fragrance,Cash on Delivery,4,3510.32,20,11233.02,2024,February,Saturday
265,05ORD100869,2024-06-12,Premium,South,Wellness,Debit Card,2,1953.85,11,3477.85,2024,June,Wednesday
149,05ORD100322,2025-04-28,Salon,West,Haircare,UPI,3,3177.95,25,7150.39,2025,April,Monday
375,05ORD100746,2024-08-21,Regular,Central,Haircare,Cash on Delivery,1,1536.61,1,1521.24,2024,August,Wednesday

## Task 20

Rename Discount_Percent to Discount.

In [96]:
df.rename(columns={"Discount_Percent":"Discount"})

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount,Order_Value,Order_Year,Order_Month,Order_Day
0,05ORD100522,2024-10-14,Salon,North,Skincare,Credit Card,2,2460.12,23,3788.58,2024,October,Monday
1,05ORD100738,2025-05-30,Salon,Central,Skincare,Wallet,4,4998.47,36,12796.08,2025,May,Friday
2,05ORD100741,2025-03-06,Premium,West,Makeup,Credit Card,5,2486.68,35,8081.71,2025,March,Thursday
3,05ORD100661,2025-08-09,Salon,South,Skincare,Credit Card,2,1274.18,10,2293.52,2025,August,Saturday
4,05ORD100412,2025-08-25,Salon,West,Fragrance,Credit Card,2,2581.16,31,3562.00,2025,August,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,05ORD100107,2024-11-23,First-Time,East,Skincare,Credit Card,1,521.25,25,390.94,2024,November,Saturday
996,05ORD100271,2025-05-18,Regular,West,Skincare,Wallet,3,4030.10,20,9672.24,2025,May,Sunday
997,05ORD100861,2024-04-27,Salon,East,Fragrance,Cash on Delivery,2,496.40,29,704.89,2024,April,Saturday
998,05ORD100436,2025-04-12,First-Time,East,Wellness,Debit Card,1,4702.95,26,3480.18,2025,April,Saturday
999,05ORD100103,2025-05-23,Salon,East,Makeup,Wallet,2,3805.41,21,6012.55,2025,May,Friday

## Task 21

Change the column name back from Discount to Discount_Percent.

In [97]:
df.rename(columns={"Discount":"Discount_Percent"})

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
0,05ORD100522,2024-10-14,Salon,North,Skincare,Credit Card,2,2460.12,23,3788.58,2024,October,Monday
1,05ORD100738,2025-05-30,Salon,Central,Skincare,Wallet,4,4998.47,36,12796.08,2025,May,Friday
2,05ORD100741,2025-03-06,Premium,West,Makeup,Credit Card,5,2486.68,35,8081.71,2025,March,Thursday
3,05ORD100661,2025-08-09,Salon,South,Skincare,Credit Card,2,1274.18,10,2293.52,2025,August,Saturday
4,05ORD100412,2025-08-25,Salon,West,Fragrance,Credit Card,2,2581.16,31,3562.00,2025,August,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,05ORD100107,2024-11-23,First-Time,East,Skincare,Credit Card,1,521.25,25,390.94,2024,November,Saturday
996,05ORD100271,2025-05-18,Regular,West,Skincare,Wallet,3,4030.10,20,9672.24,2025,May,Sunday
997,05ORD100861,2024-04-27,Salon,East,Fragrance,Cash on Delivery,2,496.40,29,704.89,2024,April,Saturday
998,05ORD100436,2025-04-12,First-Time,East,Wellness,Debit Card,1,4702.95,26,3480.18,2025,April,Saturday
999,05ORD100103,2025-05-23,Salon,East,Makeup,Wallet,2,3805.41,21,6012.55,2025,May,Friday

## Task 22

Set Order_ID as the index.

In [98]:
df.set_index("Order_ID")

,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
Order_ID,,,,,,,,,,,,
05ORD100522,2024-10-14,Salon,North,Skincare,Credit Card,2,2460.12,23,3788.58,2024,October,Monday
05ORD100738,2025-05-30,Salon,Central,Skincare,Wallet,4,4998.47,36,12796.08,2025,May,Friday
05ORD100741,2025-03-06,Premium,West,Makeup,Credit Card,5,2486.68,35,8081.71,2025,March,Thursday
05ORD100661,2025-08-09,Salon,South,Skincare,Credit Card,2,1274.18,10,2293.52,2025,August,Saturday
05ORD100412,2025-08-25,Salon,West,Fragrance,Credit Card,2,2581.16,31,3562.00,2025,August,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...
05ORD100107,2024-11-23,First-Time,East,Skincare,Credit Card,1,521.25,25,390.94,2024,November,Saturday
05ORD100271,2025-05-18,Regular,West,Skincare,Wallet,3,4030.10,20,9672.24,2025,May,Sunday
05ORD100861,2024-04-27,Salon,East,Fragrance,Cash on Delivery,2,496.40,29,704.89,2024,April,Saturday
05ORD100436,2025-04-12,First-Time,East,Wellness,Debit Card,1,4702.95,26,3480.18,2025,April,Saturday
05ORD100103,2025-05-23,Salon,East,Makeup,Wallet,2,3805.41,21,6012.55,2025,May,Friday

## Task 23

Reset the index back to default integer index.

In [99]:
df.reset_index(drop=True)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
0,05ORD100522,2024-10-14,Salon,North,Skincare,Credit Card,2,2460.12,23,3788.58,2024,October,Monday
1,05ORD100738,2025-05-30,Salon,Central,Skincare,Wallet,4,4998.47,36,12796.08,2025,May,Friday
2,05ORD100741,2025-03-06,Premium,West,Makeup,Credit Card,5,2486.68,35,8081.71,2025,March,Thursday
3,05ORD100661,2025-08-09,Salon,South,Skincare,Credit Card,2,1274.18,10,2293.52,2025,August,Saturday
4,05ORD100412,2025-08-25,Salon,West,Fragrance,Credit Card,2,2581.16,31,3562.00,2025,August,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,05ORD100107,2024-11-23,First-Time,East,Skincare,Credit Card,1,521.25,25,390.94,2024,November,Saturday
996,05ORD100271,2025-05-18,Regular,West,Skincare,Wallet,3,4030.10,20,9672.24,2025,May,Sunday
997,05ORD100861,2024-04-27,Salon,East,Fragrance,Cash on Delivery,2,496.40,29,704.89,2024,April,Saturday
998,05ORD100436,2025-04-12,First-Time,East,Wellness,Debit Card,1,4702.95,26,3480.18,2025,April,Saturday
999,05ORD100103,2025-05-23,Salon,East,Makeup,Wallet,2,3805.41,21,6012.55,2025,May,Friday

## Task 24

Sort the DataFrame by Order_Value in descending order.

In [100]:
df.sort_values(by="Order_Value",ascending=False)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
449,05ORD100674,2024-09-15,First-Time,West,Fragrance,Wallet,5,4936.75,3,23943.24,2024,September,Sunday
567,05ORD100305,2024-01-19,Salon,North,Makeup,Wallet,5,4920.00,4,23616.00,2024,January,Friday
26,05ORD100102,2024-02-29,Premium,North,Fragrance,Credit Card,5,4985.97,6,23434.06,2024,February,Thursday
930,05ORD100565,2024-12-20,First-Time,East,Skincare,UPI,5,4618.03,4,22166.54,2024,December,Friday
650,05ORD100195,2025-07-07,Salon,East,Makeup,Debit Card,5,4715.60,9,21455.98,2025,July,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,05ORD100298,2025-10-17,Regular,Central,Haircare,Cash on Delivery,2,102.67,39,125.26,2025,October,Friday
310,05ORD100595,2025-08-26,Premium,East,Skincare,Wallet,1,139.64,15,118.69,2025,August,Tuesday
609,05ORD100607,2024-02-25,Regular,North,Haircare,Cash on Delivery,1,107.20,21,84.69,2024,February,Sunday
656,05ORD100580,2025-02-02,Premium,West,Skincare,Credit Card,1,109.94,24,83.55,2025,February,Sunday
389,05ORD100775,2025-09-18,Premium,South,Wellness,Debit Card,1,140.09,41,82.65,2025,September,Thursday

## Task 25

Sort the DataFrame by Quantity ascending and Unit_Price descending.

In [101]:
df.sort_values(by=["Quantity","Unit_Price"],ascending=[True,False])

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
841,05ORD100726,2024-06-16,Premium,West,Haircare,UPI,1,4988.26,3,4838.61,2024,June,Sunday
772,05ORD100318,2025-12-21,Regular,East,Makeup,Cash on Delivery,1,4964.53,6,4666.66,2025,December,Sunday
949,05ORD100567,2024-07-18,First-Time,North,Haircare,Credit Card,1,4964.39,44,2780.06,2024,July,Thursday
586,05ORD100538,2025-06-15,Premium,Central,Wellness,Wallet,1,4952.77,16,4160.33,2025,June,Sunday
424,05ORD100434,2024-07-24,First-Time,South,Fragrance,UPI,1,4928.22,37,3104.78,2024,July,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,05ORD100515,2025-03-28,Regular,South,Fragrance,Wallet,5,230.62,29,818.70,2025,March,Friday
267,05ORD100381,2024-02-20,First-Time,South,Wellness,UPI,5,199.93,30,699.76,2024,February,Tuesday
562,05ORD100835,2024-02-28,Regular,South,Skincare,Wallet,5,180.51,9,821.32,2024,February,Wednesday
321,05ORD100149,2025-08-19,Salon,South,Skincare,Cash on Delivery,5,143.22,24,544.24,2025,August,Tuesday
906,05ORD100730,2024-05-16,Salon,Central,Makeup,Credit Card,5,132.63,4,636.62,2024,May,Thursday

## Task 26

Filter all rows where Region is North.

In [102]:
df.query('Region=="North"')

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
0,05ORD100522,2024-10-14,Salon,North,Skincare,Credit Card,2,2460.12,23,3788.58,2024,October,Monday
7,05ORD100514,2025-02-18,Salon,North,Makeup,Cash on Delivery,3,1987.87,40,3578.17,2025,February,Tuesday
8,05ORD100860,2024-02-12,Salon,North,Fragrance,Cash on Delivery,5,2449.84,2,12004.22,2024,February,Monday
9,05ORD100137,2025-10-02,Premium,North,Skincare,Cash on Delivery,2,4275.19,19,6925.81,2025,October,Thursday
16,05ORD100281,2024-09-28,First-Time,North,Wellness,Debit Card,1,1500.89,16,1260.75,2024,September,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,05ORD100563,2024-09-16,First-Time,North,Wellness,Cash on Delivery,4,315.47,28,908.55,2024,September,Monday
965,05ORD100022,2024-08-12,Salon,North,Fragrance,Wallet,2,4576.73,29,6498.96,2024,August,Monday
966,05ORD100314,2024-05-28,Salon,North,Haircare,Wallet,1,198.76,31,137.14,2024,May,Tuesday
968,05ORD100161,2025-02-01,Regular,North,Makeup,Wallet,2,194.76,22,303.83,2025,February,Saturday
969,05ORD100277,2025-01-17,Regular,North,Fragrance,Debit Card,3,4344.84,27,9515.20,2025,January,Friday

## Task 27

Filter all rows where Payment_Method is UPI.

In [103]:
df.query('Payment_Method=="UPI"')

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
10,05ORD100812,2024-11-02,First-Time,South,Makeup,UPI,5,1352.61,12,5951.48,2024,November,Saturday
14,05ORD100939,2025-08-11,Premium,East,Haircare,UPI,1,537.66,23,414.00,2025,August,Monday
34,05ORD100371,2024-01-06,Salon,Central,Makeup,UPI,2,785.70,26,1162.84,2024,January,Saturday
35,05ORD100199,2024-11-03,Salon,East,Makeup,UPI,2,3218.56,1,6372.75,2024,November,Sunday
50,05ORD100571,2025-10-28,First-Time,Central,Makeup,UPI,1,3994.43,23,3075.71,2025,October,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
971,05ORD100192,2024-07-27,First-Time,Central,Wellness,UPI,2,4796.11,31,6618.63,2024,July,Saturday
973,05ORD100806,2025-03-31,Salon,South,Wellness,UPI,3,2382.21,17,5931.70,2025,March,Monday
980,05ORD100131,2024-02-05,First-Time,South,Fragrance,UPI,5,1498.99,37,4721.82,2024,February,Monday
986,05ORD100459,2025-05-27,First-Time,Central,Skincare,UPI,3,677.00,28,1462.32,2025,May,Tuesday
992,05ORD100021,2024-12-01,First-Time,East,Haircare,UPI,3,4788.41,14,12354.10,2024,December,Sunday

## Task 28

Filter all rows where Quantity is greater than 3.

In [104]:
df.query('Quantity>3')

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
1,05ORD100738,2025-05-30,Salon,Central,Skincare,Wallet,4,4998.47,36,12796.08,2025,May,Friday
2,05ORD100741,2025-03-06,Premium,West,Makeup,Credit Card,5,2486.68,35,8081.71,2025,March,Thursday
8,05ORD100860,2024-02-12,Salon,North,Fragrance,Cash on Delivery,5,2449.84,2,12004.22,2024,February,Monday
10,05ORD100812,2024-11-02,First-Time,South,Makeup,UPI,5,1352.61,12,5951.48,2024,November,Saturday
11,05ORD100077,2025-05-10,Regular,South,Makeup,Debit Card,5,1316.80,36,4213.76,2025,May,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,05ORD100100,2025-05-06,First-Time,South,Wellness,Wallet,5,3382.01,18,13866.24,2025,May,Tuesday
984,05ORD100373,2024-06-18,Regular,West,Wellness,Cash on Delivery,5,3254.58,38,10089.20,2024,June,Tuesday
985,05ORD100088,2024-10-26,Premium,West,Skincare,Debit Card,4,1697.56,31,4685.27,2024,October,Saturday
987,05ORD100331,2025-05-15,Salon,East,Fragrance,Debit Card,5,1052.64,42,3052.66,2025,May,Thursday
994,05ORD100072,2024-07-23,Premium,East,Skincare,Wallet,4,2480.76,35,6449.98,2024,July,Tuesday

## Task 29

Filter all rows where Order_Value is above 5000.

In [105]:
df.query('Order_Value>5000')

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
1,05ORD100738,2025-05-30,Salon,Central,Skincare,Wallet,4,4998.47,36,12796.08,2025,May,Friday
2,05ORD100741,2025-03-06,Premium,West,Makeup,Credit Card,5,2486.68,35,8081.71,2025,March,Thursday
8,05ORD100860,2024-02-12,Salon,North,Fragrance,Cash on Delivery,5,2449.84,2,12004.22,2024,February,Monday
9,05ORD100137,2025-10-02,Premium,North,Skincare,Cash on Delivery,2,4275.19,19,6925.81,2025,October,Thursday
10,05ORD100812,2024-11-02,First-Time,South,Makeup,UPI,5,1352.61,12,5951.48,2024,November,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,05ORD100021,2024-12-01,First-Time,East,Haircare,UPI,3,4788.41,14,12354.10,2024,December,Sunday
993,05ORD100701,2025-08-25,Regular,West,Fragrance,Wallet,3,4843.18,5,13803.06,2025,August,Monday
994,05ORD100072,2024-07-23,Premium,East,Skincare,Wallet,4,2480.76,35,6449.98,2024,July,Tuesday
996,05ORD100271,2025-05-18,Regular,West,Skincare,Wallet,3,4030.10,20,9672.24,2025,May,Sunday
999,05ORD100103,2025-05-23,Salon,East,Makeup,Wallet,2,3805.41,21,6012.55,2025,May,Friday

## Task 30

Filter rows where Discount_Percent is between 10 and 20.

In [106]:
df.query('Discount_Percent>10 and Discount_Percent<20')

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
5,05ORD100679,2024-03-15,First-Time,East,Fragrance,Debit Card,1,212.37,15,180.51,2024,March,Friday
9,05ORD100137,2025-10-02,Premium,North,Skincare,Cash on Delivery,2,4275.19,19,6925.81,2025,October,Thursday
10,05ORD100812,2024-11-02,First-Time,South,Makeup,UPI,5,1352.61,12,5951.48,2024,November,Saturday
16,05ORD100281,2024-09-28,First-Time,North,Wellness,Debit Card,1,1500.89,16,1260.75,2024,September,Saturday
23,05ORD100528,2024-06-09,First-Time,East,Makeup,Cash on Delivery,1,3994.76,12,3515.39,2024,June,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,05ORD100344,2024-08-04,Premium,West,Skincare,Wallet,5,1197.20,12,5267.68,2024,August,Sunday
977,05ORD100770,2024-02-01,Premium,South,Haircare,Wallet,2,1946.85,19,3153.90,2024,February,Thursday
983,05ORD100100,2025-05-06,First-Time,South,Wellness,Wallet,5,3382.01,18,13866.24,2025,May,Tuesday
990,05ORD100122,2025-07-14,Salon,West,Makeup,Wallet,3,837.10,16,2109.49,2025,July,Monday
992,05ORD100021,2024-12-01,First-Time,East,Haircare,UPI,3,4788.41,14,12354.10,2024,December,Sunday

## Task 31

Filter rows where Product_Category belongs to a given list of two categories.

In [107]:
df.query("Product_Category in ['Skincare', 'Makeup']")

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
0,05ORD100522,2024-10-14,Salon,North,Skincare,Credit Card,2,2460.12,23,3788.58,2024,October,Monday
1,05ORD100738,2025-05-30,Salon,Central,Skincare,Wallet,4,4998.47,36,12796.08,2025,May,Friday
2,05ORD100741,2025-03-06,Premium,West,Makeup,Credit Card,5,2486.68,35,8081.71,2025,March,Thursday
3,05ORD100661,2025-08-09,Salon,South,Skincare,Credit Card,2,1274.18,10,2293.52,2025,August,Saturday
6,05ORD100627,2025-12-21,Regular,Central,Skincare,Credit Card,2,3489.43,42,4047.74,2025,December,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,05ORD100615,2025-03-27,Salon,Central,Skincare,Credit Card,1,2389.92,5,2270.42,2025,March,Thursday
994,05ORD100072,2024-07-23,Premium,East,Skincare,Wallet,4,2480.76,35,6449.98,2024,July,Tuesday
995,05ORD100107,2024-11-23,First-Time,East,Skincare,Credit Card,1,521.25,25,390.94,2024,November,Saturday
996,05ORD100271,2025-05-18,Regular,West,Skincare,Wallet,3,4030.10,20,9672.24,2025,May,Sunday
999,05ORD100103,2025-05-23,Salon,East,Makeup,Wallet,2,3805.41,21,6012.55,2025,May,Friday

## Task 32

Find all unique values in Customer_Segment.

In [108]:
df["Customer_Segment"].unique()

<StringArray>
['Salon', 'Premium', 'First-Time', 'Regular']
Length: 4, dtype: str

## Task 33

Count the number of unique values in Product_Category.

In [109]:
df["Product_Category"].nunique()

5

## Task 34

Display value counts for Region.

In [110]:
df["Region"].value_counts()

Region
South      225
Central    205
North      199
East       197
West       174
Name: count, dtype: int64

## Task 35

Display value counts for Payment_Method.

In [111]:
df["Payment_Method"].value_counts()

Payment_Method
Wallet              210
Debit Card          207
UPI                 202
Cash on Delivery    192
Credit Card         189
Name: count, dtype: int64

## Task 36

Find the minimum, maximum, and mean of Unit_Price.

In [112]:
df["Unit_Price"].min(),df["Unit_Price"].max(),df["Unit_Price"].mean()

(np.float64(102.67), np.float64(4998.47), np.float64(2559.76304))

## Task 37

Find the total sum of Order_Value.

In [113]:
df["Order_Value"].sum()

np.float64(4903644.859999999)

## Task 38

Find the median of Quantity.

In [114]:
df["Quantity"].median()

np.float64(2.0)

## Task 39

Find the standard deviation of Order_Value.

In [115]:
df["Order_Value"].std()

np.float64(4472.927876206425)

## Task 40

Create a new column Gross_Value as Quantity multiplied by Unit_Price.

In [116]:
df["Gross_Value"]=df["Quantity"]*df["Unit_Price"]
df

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Gross_Value
0,05ORD100522,2024-10-14,Salon,North,Skincare,Credit Card,2,2460.12,23,3788.58,2024,October,Monday,4920.24
1,05ORD100738,2025-05-30,Salon,Central,Skincare,Wallet,4,4998.47,36,12796.08,2025,May,Friday,19993.88
2,05ORD100741,2025-03-06,Premium,West,Makeup,Credit Card,5,2486.68,35,8081.71,2025,March,Thursday,12433.40
3,05ORD100661,2025-08-09,Salon,South,Skincare,Credit Card,2,1274.18,10,2293.52,2025,August,Saturday,2548.36
4,05ORD100412,2025-08-25,Salon,West,Fragrance,Credit Card,2,2581.16,31,3562.00,2025,August,Monday,5162.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,05ORD100107,2024-11-23,First-Time,East,Skincare,Credit Card,1,521.25,25,390.94,2024,November,Saturday,521.25
996,05ORD100271,2025-05-18,Regular,West,Skincare,Wallet,3,4030.10,20,9672.24,2025,May,Sunday,12090.30
997,05ORD100861,2024-04-27,Salon,East,Fragrance,Cash on Delivery,2,496.40,29,704.89,2024,April,Saturday,992.80
998,05ORD100436,2025-04-12,First-Time,East,Wellness,Debit Card,1,4702.95,26,3480.18,2025,April,Saturday,4702.95
999,05ORD100103,2025-05-23,Salon,East,Makeup,Wallet,2,3805.41,21,6012.55,2025,May,Friday,7610.82

## Task 41

Verify whether Gross_Value and Order_Value are consistent after discount calculation.

## Task 42

Create a new column Discount_Amount.

In [117]:
df["Discount_amount"]=df["Order_Value"]*(df["Discount_Percent"]/100)
df

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Gross_Value,Discount_amount
0,05ORD100522,2024-10-14,Salon,North,Skincare,Credit Card,2,2460.12,23,3788.58,2024,October,Monday,4920.24,871.3734
1,05ORD100738,2025-05-30,Salon,Central,Skincare,Wallet,4,4998.47,36,12796.08,2025,May,Friday,19993.88,4606.5888
2,05ORD100741,2025-03-06,Premium,West,Makeup,Credit Card,5,2486.68,35,8081.71,2025,March,Thursday,12433.40,2828.5985
3,05ORD100661,2025-08-09,Salon,South,Skincare,Credit Card,2,1274.18,10,2293.52,2025,August,Saturday,2548.36,229.3520
4,05ORD100412,2025-08-25,Salon,West,Fragrance,Credit Card,2,2581.16,31,3562.00,2025,August,Monday,5162.32,1104.2200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,05ORD100107,2024-11-23,First-Time,East,Skincare,Credit Card,1,521.25,25,390.94,2024,November,Saturday,521.25,97.7350
996,05ORD100271,2025-05-18,Regular,West,Skincare,Wallet,3,4030.10,20,9672.24,2025,May,Sunday,12090.30,1934.4480
997,05ORD100861,2024-04-27,Salon,East,Fragrance,Cash on Delivery,2,496.40,29,704.89,2024,April,Saturday,992.80,204.4181
998,05ORD100436,2025-04-12,First-Time,East,Wellness,Debit Card,1,4702.95,26,3480.18,2025,April,Saturday,4702.95,904.8468
999,05ORD100103,2025-05-23,Salon,East,Makeup,Wallet,2,3805.41,21,6012.55,2025,May,Friday,7610.82,1262.6355

## Task 43

Create a new column High_Value_Order where Order_Value > 5000 is Yes otherwise No.

In [118]:
import numpy as np
df["High_Value_Order"]=np.where(df["Order_Value"]>5000,"Yes","No")
df

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Gross_Value,Discount_amount,High_Value_Order
0,05ORD100522,2024-10-14,Salon,North,Skincare,Credit Card,2,2460.12,23,3788.58,2024,October,Monday,4920.24,871.3734,No
1,05ORD100738,2025-05-30,Salon,Central,Skincare,Wallet,4,4998.47,36,12796.08,2025,May,Friday,19993.88,4606.5888,Yes
2,05ORD100741,2025-03-06,Premium,West,Makeup,Credit Card,5,2486.68,35,8081.71,2025,March,Thursday,12433.40,2828.5985,Yes
3,05ORD100661,2025-08-09,Salon,South,Skincare,Credit Card,2,1274.18,10,2293.52,2025,August,Saturday,2548.36,229.3520,No
4,05ORD100412,2025-08-25,Salon,West,Fragrance,Credit Card,2,2581.16,31,3562.00,2025,August,Monday,5162.32,1104.2200,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,05ORD100107,2024-11-23,First-Time,East,Skincare,Credit Card,1,521.25,25,390.94,2024,November,Saturday,521.25,97.7350,No
996,05ORD100271,2025-05-18,Regular,West,Skincare,Wallet,3,4030.10,20,9672.24,2025,May,Sunday,12090.30,1934.4480,Yes
997,05ORD100861,2024-04-27,Salon,East,Fragrance,Cash on Delivery,2,496.40,29,704.89,2024,April,Saturday,992.80,204.4181,No
998,05ORD100436,2025-04-12,First-Time,East,Wellness,Debit Card,1,4702.95,26,3480.18,2025,April,Saturday,4702.95,904.8468,No
999,05ORD100103,2025-05-23,Salon,East,Makeup,Wallet,2,3805.41,21,6012.55,2025,May,Friday,7610.82,1262.6355,Yes

## Task 44

Use apply() to categorize Unit_Price into Low, Medium, High.

## Task 45

Find the top 10 highest Order_Value rows.

In [123]:
df.nlargest(10,"Order_Value")

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Gross_Value,Discount_amount,High_Value_Order
449,05ORD100674,2024-09-15,First-Time,West,Fragrance,Wallet,5,4936.75,3,23943.24,2024,September,Sunday,24683.75,718.2972,Yes
567,05ORD100305,2024-01-19,Salon,North,Makeup,Wallet,5,4920.00,4,23616.00,2024,January,Friday,24600.00,944.6400,Yes
26,05ORD100102,2024-02-29,Premium,North,Fragrance,Credit Card,5,4985.97,6,23434.06,2024,February,Thursday,24929.85,1406.0436,Yes
930,05ORD100565,2024-12-20,First-Time,East,Skincare,UPI,5,4618.03,4,22166.54,2024,December,Friday,23090.15,886.6616,Yes
650,05ORD100195,2025-07-07,Salon,East,Makeup,Debit Card,5,4715.60,9,21455.98,2025,July,Monday,23578.00,1931.0382,Yes
238,05ORD100193,2024-09-23,First-Time,East,Makeup,Debit Card,5,4508.03,8,20736.94,2024,September,Monday,22540.15,1658.9552,Yes
847,05ORD100407,2025-01-23,Premium,South,Fragrance,Cash on Delivery,5,4388.17,7,20404.99,2025,January,Thursday,21940.85,1428.3493,Yes
587,05ORD100621,2024-07-19,Salon,East,Skincare,Debit Card,5,4596.53,12,20224.73,2024,July,Friday,22982.65,2426.9676,Yes
338,05ORD100873,2024-01-11,Premium,East,Skincare,Cash on Delivery,5,4904.97,20,19619.88,2024,January,Thursday,24524.85,3923.9760,Yes
408,05ORD100052,2025-02-23,Premium,South,Wellness,Wallet,5,4752.22,18,19484.10,2025,February,Sunday,23761.10,3507.1380,Yes

## Task 46

Find the bottom 10 lowest Order_Value rows.

In [124]:
df.nsmallest(10,"Order_Value")

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Gross_Value,Discount_amount,High_Value_Order
389,05ORD100775,2025-09-18,Premium,South,Wellness,Debit Card,1,140.09,41,82.65,2025,September,Thursday,140.09,33.8865,No
656,05ORD100580,2025-02-02,Premium,West,Skincare,Credit Card,1,109.94,24,83.55,2025,February,Sunday,109.94,20.0520,No
609,05ORD100607,2024-02-25,Regular,North,Haircare,Cash on Delivery,1,107.20,21,84.69,2024,February,Sunday,107.20,17.7849,No
310,05ORD100595,2025-08-26,Premium,East,Skincare,Wallet,1,139.64,15,118.69,2025,August,Tuesday,139.64,17.8035,No
697,05ORD100298,2025-10-17,Regular,Central,Haircare,Cash on Delivery,2,102.67,39,125.26,2025,October,Friday,205.34,48.8514,No
475,05ORD100989,2025-04-05,Regular,Central,Fragrance,Cash on Delivery,1,205.81,39,125.54,2025,April,Saturday,205.81,48.9606,No
749,05ORD100920,2024-03-03,Premium,East,Haircare,Cash on Delivery,1,143.74,12,126.49,2024,March,Sunday,143.74,15.1788,No
181,05ORD100671,2024-08-03,Premium,North,Wellness,Debit Card,1,165.25,19,133.85,2024,August,Saturday,165.25,25.4315,No
966,05ORD100314,2024-05-28,Salon,North,Haircare,Wallet,1,198.76,31,137.14,2024,May,Tuesday,198.76,42.5134,No
57,05ORD100011,2025-07-02,Premium,Central,Wellness,UPI,1,182.15,21,143.90,2025,July,Wednesday,182.15,30.2190,No

## Task 47

Group by Region and calculate average Order_Value.

In [125]:
df.groupby("Region")["Order_Value"].mean()

Region
Central    5094.528439
East       4573.200152
North      5051.579950
South      4685.353556
West       5165.960575
Name: Order_Value, dtype: float64

## Task 48

Group by Product_Category and calculate total sales.

In [126]:
df.groupby("Product_Category")['Quantity'].sum()

Product_Category
Fragrance    563
Haircare     411
Makeup       510
Skincare     491
Wellness     485
Name: Quantity, dtype: int64

## Task 49

Group by Payment_Method and calculate total Quantity sold.

In [127]:
df.groupby("Payment_Method")['Quantity'].sum()

Payment_Method
Cash on Delivery    482
Credit Card         447
Debit Card          480
UPI                 511
Wallet              540
Name: Quantity, dtype: int64

## Task 50

Group by Customer_Segment and calculate average discount percentage.

In [128]:
df.groupby("Customer_Segment")['Discount_Percent'].mean()

Customer_Segment
First-Time    24.080169
Premium       21.777344
Regular       22.231939
Salon         23.774590
Name: Discount_Percent, dtype: float64

## Task 51

Perform multi-level grouping by Region and Product_Category and compute total Order_Value.

In [119]:
results = df.groupby(['Region', 'Product_Category'])['Order_Value'].sum().reset_index()
print(results)

     Region Product_Category  Order_Value
0   Central        Fragrance    224634.49
1   Central         Haircare    251810.77
2   Central           Makeup    138805.79
3   Central         Skincare    211082.40
4   Central         Wellness    218044.88
5      East        Fragrance    155817.99
6      East         Haircare    120066.99
7      East           Makeup    223612.33
8      East         Skincare    275622.12
9      East         Wellness    125801.00
10    North        Fragrance    261739.54
11    North         Haircare    138759.02
12    North           Makeup    248284.13
13    North         Skincare    175229.17
14    North         Wellness    181252.55
15    South        Fragrance    241907.29
16    South         Haircare    172857.07
17    South           Makeup    211856.16
18    South         Skincare    168583.97
19    South         Wellness    259000.06
20     West        Fragrance    240132.06
21     West         Haircare    164180.76
22     West           Makeup    157002.01
23     West         Skincare    132961.52
24     West         Wellness    204600.79

## Task 52

Aggregate Quantity, Unit_Price, and Order_Value with multiple statistics using agg().

In [120]:
aggregated = df[['Quantity', 'Unit_Price', 'Order_Value']].agg(['sum', 'mean', 'min', 'max', 'std'])
aggregated

         Quantity    Unit_Price   Order_Value
sum   2460.000000  2.559763e+06  4.903645e+06
mean     2.460000  2.559763e+03  4.903645e+03
min      1.000000  1.026700e+02  8.265000e+01
max      5.000000  4.998470e+03  2.394324e+04
std      1.443081  1.448333e+03  4.472928e+03

## Task 53

Create a pivot table showing total Order_Value by Region and Payment_Method.

## Task 54

Create a pivot table showing average Unit_Price by Product_Category and Customer_Segment.

## Task 55

Count the number of orders placed in each month.

In [121]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
orders = df.groupby(df['Order_Date'].dt.to_period('M')).size()
orders

Order_Date
2024-01    55
2024-02    55
2024-03    39
2024-04    40
2024-05    39
2024-06    31
2024-07    39
2024-08    56
2024-09    31
2024-10    25
2024-11    34
2024-12    47
2025-01    49
2025-02    34
2025-03    46
2025-04    38
2025-05    51
2025-06    38
2025-07    39
2025-08    61
2025-09    41
2025-10    41
2025-11    33
2025-12    38
Freq: M, dtype: int64

## Task 56

Find the month with the highest total sales.

## Task 57

Find the region with the highest average order value.

## Task 58

Find the product category with the highest total quantity sold.

## Task 59

Use query() to filter rows where Quantity >= 2 and Discount_Percent >= 15.

## Task 60

Select only Order_ID, Region, Product_Category, and Order_Value columns.

## Task 61

Reorder the columns in any meaningful custom order.

## Task 62

Find rows where Order_Value is above the overall average order value.

## Task 63

Find rows where Unit_Price is below the 25th percentile.

## Task 64

Find the correlation between Quantity, Unit_Price, Discount_Percent, and Order_Value.

## Task 65

Export the top 50 highest value orders to a CSV file.

## Task 66

Create a bar chart of total Order_Value by Region using Matplotlib.

## Task 67

Create a bar chart of total Quantity sold by Product_Category using Seaborn.

## Task 68

Create a histogram of Unit_Price using Matplotlib.

## Task 69

Create a histogram of Order_Value with KDE using Seaborn.

## Task 70

Create a boxplot of Order_Value by Region.

## Task 71

Create a boxplot of Unit_Price by Payment_Method.

## Task 72

Create a countplot of Customer_Segment.

## Task 73

Create a pie chart of Payment_Method distribution.

## Task 74

Create a line chart of monthly total sales.

## Task 75

Create a heatmap of correlation among numerical columns.

## Task 76

Create a scatter plot of Unit_Price vs Order_Value.

## Task 77

Create a scatter plot of Quantity vs Order_Value colored by Region using Seaborn.

## Task 78

Create a violin plot of Order_Value by Product_Category.

## Task 79

Create a stacked bar style plot of monthly sales by Region.

## Task 80

Create a pairplot for Quantity, Unit_Price, Discount_Percent, and Order_Value.